apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-micro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-micro-registry
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-micro-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-micro-registry
subjects:
  - kind: ServiceAccount
    name: go-micro
