---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: | 
    appendonly yes
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: quay.io/acancell-redhat-talks/ibm_txc_24_rome/onlineboutique-micro-ppc64le/valkey:latest
          ports:
            - containerPort: 6379
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          resources:
            limits:
              memory: 256Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 200Mi
          volumeMounts:
            - mountPath: /etc/redis
              name: redis-conf
            - mountPath: /data
              name: redis-data-claim
          args:
            - "/etc/redis/redis.conf"
      volumes:
      - name: redis-conf
        configMap:
          name: redis-conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
    - name: tls-redis
      port: 6379
      targetPort: 6379
